apiVersion: v1
kind: Service
metadata:
  name: weather-ui-service
namespace: weather
spec:
  type: LoadBalancer
  selector:
    app: weather-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
